# Generated by Django 2.2.19 on 2021-03-06 03:47

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name="donor's name")),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('email', models.EmailField(max_length=254)),
                ('website', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Herb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('common_name', models.CharField(max_length=100)),
                ('binomial', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PreparationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name of preparation type')),
            ],
        ),
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name of volunteer')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Remedy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='remedy name')),
                ('quantity', models.IntegerField()),
                ('units', models.CharField(max_length=30)),
                ('source_of_herbs', models.TextField()),
                ('date_made', models.DateField()),
                ('best_by_date', models.DateField()),
                ('contains_alcohol', models.BooleanField(default=False)),
                ('notes', models.TextField()),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.Donor')),
                ('herbs', models.ManyToManyField(to='inventory.Herb')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.PreparationType')),
            ],
        ),
    ]
