# Generated by Django 2.2.19 on 2021-03-06 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='website',
            field=models.URLField(blank=True),
        ),
    ]
