# Generated by Django 2.2.19 on 2021-03-06 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20210305_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remedy',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
