# Generated by Django 2.2.19 on 2021-03-15 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_auto_20210314_2315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='contains_alcohol',
        ),
    ]
